GET http://localhost:8010/api/charactersheets

###

GET http://localhost:8010/api/charactersheets/5eb6a351047fe579956c09b8

###

POST http://localhost:8010/api/charactersheets  HTTP/1.1
content-type: application/json

 {
    "name": "Another one",
    "description": "i am sure of it",
    "race": "human",
    "currentHitPoints": 15,
    "maxHitPoints": 18,
    "armorClass": 12,
    "personalityTraits": "demigod"
  },