#GET http://localhost:8010/api/charactersheets
GET https://talesofapirate.com/dnd/api/charactersheets
#POST https://talesofapirate.com/dnd/api/charactersheets  HTTP/1.1

###

GET http://localhost:8010/api/charactersheets/5eb6a351047fe579956c09b8

###

###POST http://localhost:8010/api/charactersheets  HTTP/1.1
POST https://talesofapirate.com/dnd/api/charactersheets  HTTP/1.1
content-type: application/json

 {
    "name": "Elissa",
    "description": "i am sure of it",
    "race": "dwarf",
    "currentHitPoints": 15,
    "maxHitPoints": 18,
    "armorClass": 12,
    "personalityTraits": "drinking beer like no other girl"
  },