
@prod=https://talesofapirate.com/dnd
@local=http://localhost:8010
@host={{local}}
@token=REPLACE_ME

###
GET {{host}}/health
###
GET {{host}}/api/characters
authorization: Bearer {{token}}
                      
###
GET {{host}}/api/characters/5eb9009e2a00469b59fa60e3
###
DELETE {{host}}/api/characters/5eb9009e2a00469b59fa60e3
### Client ID    gOkg8ZUdwKp1MmVE0EXh97Nlg0m5zgw1
POST {{host}}/api/characters  HTTP/1.1
content-type: application/json
authorization: Bearer {{token}}

 {
    "name": "Gwendoline",
    "description": "i am sure of it",
    "race": "dwarf",
    "currentHitPoints": 15,
    "maxHitPoints": 2,
    "armorClass": 3,
    "personalityTraits": "lalala"
  },

### user ------------------

GET {{host}}/api/user
authorization: Bearer {{token}}

###
PUT {{host}}/api/user  HTTP/1.1
content-type: application/json
authorization: Bearer {{token}}

 {
  "id": "myid",
    "name": "username",
    "nickname": "nick"
},
