#GET http://localhost:8010/api/charactersheets
GET http://localhost:8010/api/parties

###

POST http://localhost:8010/api/parties  HTTP/1.1
content-type: application/json

 {
    "name": "Elissa",
    "description": "i am sure of it",
    "race": "dwarf",
    "currentHitPoints": 15,
    "maxHitPoints": 18,
    "armorClass": 12,
    "personalityTraits": "drinking beer like no other girl"
  },